CREATE TABLE challenge_phone (
	_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Phone key',
	name VARCHAR(255) NOT NULL COMMENT 'Phone name',
	description TEXT DEFAULT NULL COMMENT 'Notes about phone',
	image TEXT DEFAULT NULL COMMENT 'URL to iamge',
	price INT NOT NULL COMMENT 'Price in Euro cents'
) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB;

CREATE TABLE challenge_order (
	_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Order key',
	customer_name VARCHAR(255) NOT NULL COMMENT 'Customer name',
	customer_surname VARCHAR(255) NOT NULL COMMENT 'Customer surname',
	customer_email VARCHAR(255) NOT NULL COMMENT 'Customer email',
	phones VARCHAR(255) NOT NULL COMMENT 'Phones IDs comma sparated',
	total_price INT NOT NULL COMMENT 'Total price',
	created_at DATETIME NOT NULL DEFAULT NOW() COMMENT 'Creation date' 
) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB;

INSERT INTO challenge_phone(name, description, image, price) VALUES
('Apple iPad 2 CDMA', 'Also known as Apple iPad CDMA Early 2011', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad2-new.jpg', 20000),
('Apple iPad 2 Wi-Fi', 'Also known as Apple iPad Wi-Fi Early 2011', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad2-new.jpg', 20000),
('Apple iPad 2 Wi-Fi + 3G', 'Also known as Apple iPad Wi-Fi + 3G Early 2011', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad2-new.jpg', 37000),
('Apple iPad 3 Wi-Fi', 'Also known as Apple iPad Wi-Fi Early 2012, Apple iPad (3rd generation)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-3-new.jpg', 29000),
('Apple iPad 3 Wi-Fi + Cellular', 'Also known as Apple iPad Wi-Fi + 4G Early 2012, Apple iPad 3 Wi-Fi + 4G, Apple iPad (3rd generation)  CDMA available only if sold and activated for use on a CDMA network  LTE only supported on AT&T and Verizon networks in the US and  Bell, Rogers, and Telus networks in Canada', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-3-new.jpg', 40000),
('Apple iPad 4 Wi-Fi', 'Also known as Apple iPad with Retina display, Apple iPad (4th generation)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-3-new.jpg', 35000),
('Apple iPad 4 Wi-Fi + Cellular', 'Also known as Apple iPad 4 Wi-Fi + 4G, Apple iPad with Retina display, Apple iPad (4th generation)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-3-new.jpg', 50000),
('Apple iPad 9.7 (2017)', 'Supported LTE Networks  Versions: Apple iPad 9.7 Wi-Fi + Cellular (4G/LTE); Apple iPad Wi-Fi (Wi-Fi, w/o GPS)  Also known as Apple iPad (5th generation)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-97-2017.jpg', 39000),
('Apple iPad 9.7 (2018)', 'Supported LTE Networks  Versions: Apple iPad 9.7 Wi-Fi + Cellular (4G/LTE); Apple iPad Wi-Fi (Wi-Fi, w/o GPS)  Also known as Apple iPad (6th generation)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-97-2018.jpg', 35000),
('Apple iPad Air', 'Supported LTE Networks  Versions: Apple iPad Air Wi-Fi + Cellular (3G/LTE); Apple iPad Air Wi-Fi (Wi-Fi, w/o GPS)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-air.jpg', 35000),
('Apple iPad Air 2', 'Supported LTE Networks  Versions: Apple iPad Air 2 Wi-Fi + Cellular (3G/LTE); Apple iPad Air 2 Wi-Fi (Wi-Fi, w/o GPS)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-air-2-new.jpg', 44000),
('Apple iPad mini 2', 'Supported LTE Networks  Versions: Apple iPad mini 2 Wi-Fi + Cellular (3G/LTE); Apple iPad mini 2 Wi-Fi (Wi-Fi, w/o GPS)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-mini2.jpg', 27000),
('Apple iPad mini 3', 'Supported LTE Networks  Versions: Apple iPad mini 3 Wi-Fi + Cellular (3G/LTE); Apple iPad mini 3 Wi-Fi (Wi-Fi, w/o GPS)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-mini-3-new.jpg', 40000),
('Apple iPad mini 4', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/ipad-mini-41.jpg', 36000),
('Apple iPad mini Wi-Fi', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-mini-final.jpg', 20000),
('Apple iPad mini Wi-Fi + Cellular', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-mini-final.jpg', 30000),
('Apple iPad Pro 10.5 (2017)', 'Also known as Apple iPad Pro (10.5-inch)  Supported LTE Networks  Versions: Apple iPad Pro Wi-Fi + Cellular (4G/LTE); Apple iPad Pro Wi-Fi (Wi-Fi, w/o GPS)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-105-2017.jpg', 73000),
('Apple iPad Pro 12.9 (2015)', 'Also known as Apple iPad Pro (12.9-inch)  Supported LTE Networks  Versions: Apple iPad Pro Wi-Fi + Cellular (3G/LTE); Apple iPad Pro Wi-Fi (Wi-Fi, w/o GPS)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-.jpg', 85000),
('Apple iPad Pro 12.9 (2017)', 'Also known as Apple iPad Pro 12.9-inch (2nd generation)Supported LTE Networks  Versions: Apple iPad Pro Wi-Fi + Cellular (4G/LTE); Apple iPad Pro Wi-Fi (Wi-Fi, w/o GPS)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-129-2017.jpg', 90000),
('Apple iPad Pro 9.7 (2016)', 'Also known as Apple iPad Pro (9.7-inch)  Supported LTE Networks  Versions: Apple iPad Pro Wi-Fi + Cellular (3G/LTE); Apple iPad Pro Wi-Fi (Wi-Fi, w/o GPS)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-97.jpg', 69000),
('Apple iPad Wi-Fi', 'Also known as Apple iPad Wi-Fi Early 2010', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-original.jpg', 31000),
('Apple iPad Wi-Fi + 3G', 'Also known as Apple iPad Wi-Fi + 3G Early 2010.  Tablet with no GSM voice communication capabilities', 'https://cdn2.gsmarena.com/vv/bigpic/apple-ipad-original.jpg', 41000),
('Apple iPhone', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone.gif', 42000),
('Apple iPhone 3G', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone3g.jpg', 9000),
('Apple iPhone 3GS', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-3gs-ofic.jpg', 11000),
('Apple iPhone 4', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-4-ofic-final.jpg', 20000),
('Apple iPhone 4 CDMA', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone4-cdma.jpg', 15000),
('Apple iPhone 4s', 'CDMA available only if sold and activated for use on a CDMA network', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-4s-new.jpg', 19000),
('Apple iPhone 5', 'Supported LTE Networks', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-5-ofic.jpg', 34000),
('Apple iPhone 5c', 'Supported LTE Networks', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-5c-new2.jpg', 30000),
('Apple iPhone 5s', 'Supported LTE Networks', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-5s-ofic.jpg', 33000),
('Apple iPhone 6', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-6-4.jpg', 36000),
('Apple iPhone 6 Plus', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-6-plus2.jpg', 42000),
('Apple iPhone 6s', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-6s1.jpg', 50000),
('Apple iPhone 6s Plus', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-6s-plus.jpg', 47000),
('Apple iPhone 7', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-7r4.jpg', 55000),
('Apple iPhone 7 Plus', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-7-plus-r2.jpg', 69000),
('Apple iPhone 8', 'Versions:  A1863 (USA, Hong Kong, Australia, New Zealand, China)  A1905 (EMEA, UAE, LATAM, Canada, USA - AT&T/T-Mobile, Singapore); A1906 (Japan)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-8-new.jpg', 70000),
('Apple iPhone 8 Plus', 'Versions:  A1864 (USA, Hong Kong, Australia, New Zealand, China)  A1897 (EMEA, UAE, LATAM, Canada, USA - AT&T/T-Mobile, Singapore); A1898 (Japan)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-8-plus-new.jpg', 81000),
('Apple iPhone SE', 'Supported LTE Networks', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-5se-ofic.jpg', 30000),
('Apple iPhone X', 'Also known as Apple iPhone 10, Apple iPhone Ten  Versions:  A1865 (USA, Hong Kong, Australia, New Zealand, China)  A1901 (EMEA, UAE, LATAM, Canada, USA - AT&T/T-Mobile, Singapore)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-x.jpg', 100000),
('Apple Watch 38mm (1st gen)', '- Compatible with Apple iPhone 5 (or newer)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-38mm.jpg', 65000),
('Apple Watch 42mm (1st gen)', '- Compatible with Apple iPhone 5 (or newer)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-42mm.jpg', 70000),
('Apple Watch Edition 38mm (1st gen)', '- Compatible with Apple iPhone 5 (or newer)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-edition-38mm.jpg', 1100000),
('Apple Watch Edition 42mm (1st gen)', '- Compatible with Apple iPhone 5 (or newer)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-edition-42mm.jpg', 1300000),
('Apple Watch Edition Series 2 38mm', 'Series 2 requires an iPhone 5s/iOS 11 (or later)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch2-s2-edition-38mm.jpg', 145000),
('Apple Watch Edition Series 2 42mm', 'Series 2 requires an iPhone 5s/iOS 11 (or later)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch2-edition-42mm.jpg', 150000),
('Apple Watch Edition Series 3', 'Series 3 (GPS + Cellular) requires an iPhone 6/iOS 11 (or later)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-edition-series3.jpg', 145000),
('Apple Watch Series 1 Aluminum 38mm', 'Series 1 requires an iPhone 5s/iOS 11 (or later)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch2-s2-sport-38mm.jpg', 27000),
('Apple Watch Series 1 Aluminum 42mm', 'Series 1 requires an iPhone 5s/iOS 11 (or later)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch1-sport-42mm.jpg', 30000),
('Apple Watch Series 2 38mm', 'Series 2 requires an iPhone 5s/iOS 11 (or later)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch2-s2-38mm.jpg', 65000),
('Apple Watch Series 2 42mm', 'Series 2 requires an iPhone 5s/iOS 11 (or later)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch2-s2-42mm.jpg', 70000),
('Apple Watch Series 2 Aluminum 38mm', 'Series 2 requires an iPhone 5s/iOS 11 (or later)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch2-s2-sport-38mm.jpg', 42000),
('Apple Watch Series 2 Aluminum 42mm', 'Series 2 requires an iPhone 5s/iOS 11 (or later)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch2-s2-sport-42mm.jpg', 45000),
('Apple Watch Series 3', 'Series 3 (GPS + Cellular) requires an iPhone 6/iOS 11 (or later)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-series3-.jpg', 70000),
('Apple Watch Series 3 Aluminum', 'Series 3 (GPS) requires an iPhone 5s/iOS 11 (or later)  Series 3 (GPS + Cellular) requires an iPhone 6/iOS 11 (or later)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-series3-sport-.jpg', 48000),
('Apple Watch Sport 38mm (1st gen)', '- Compatible with Apple iPhone 5 (or newer)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-sport-38mm.jpg', 25000),
('Apple Watch Sport 42mm (1st gen)', '- Compatible with Apple iPhone 5 (or newer)', 'https://cdn2.gsmarena.com/vv/bigpic/apple-watch-sport-42mm2.jpg', 25000),
('Ericsson A1018s', NULL, NULL, 35000),
('Ericsson A2618', NULL, NULL, 44000),
('Ericsson A2628', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/era2628.gif', 27000),
('Ericsson A3618', NULL, NULL, 40000),
('Ericsson GA 318', NULL, NULL, 36000),
('Ericsson GA 628', NULL, NULL, 20000),
('Ericsson GF 337', NULL, NULL, 30000),
('Ericsson GF 388', NULL, NULL, 73000),
('Ericsson GF 768', NULL, NULL, 85000),
('Ericsson GF 788', NULL, NULL, 90000),
('Ericsson GF 788e', NULL, NULL, 69000),
('Ericsson GH 218', NULL, NULL, 31000),
('Ericsson GH 337', NULL, NULL, 41000),
('Ericsson GH 388', NULL, NULL, 42000),
('Ericsson GH 688', NULL, NULL, 9000),
('Ericsson GO 118', NULL, NULL, 11000),
('Ericsson GS 18', NULL, NULL, 20000),
('Ericsson GS 337', NULL, NULL, 15000),
('Ericsson I 888', NULL, NULL, 19000),
('Ericsson PF 768', NULL, NULL, 34000),
('Ericsson R250s PRO', 'Water, dust and shock resistant', NULL, 30000),
('Ericsson R310s', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/err310s.gif', 33000),
('Ericsson R320', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/err320b.gif', 36000),
('Ericsson R380', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/err380b.gif', 42000),
('Ericsson R520m', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/err520m.gif', 50000),
('Ericsson R600', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/err600.gif', 47000),
('Ericsson S 868', NULL, NULL, 55000),
('Ericsson SH 888', NULL, NULL, 69000),
('Ericsson T10s', NULL, NULL, 70000),
('Ericsson T18s', NULL, NULL, 81000),
('Ericsson T20e', NULL, NULL, 30000),
('Ericsson T20s', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/ert20s.gif', 100000),
('Ericsson T28 World', NULL, NULL, 65000),
('Ericsson T28s', NULL, NULL, 70000),
('Ericsson T29s', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/ert29.gif', 1100000),
('Ericsson T36', 'The launch has been cancelled by Ericsson!', 'https://cdn2.gsmarena.com/vv/bigpic/ert36b.gif', 1300000),
('Ericsson T39', 'The replacment for canceled T36', 'https://cdn2.gsmarena.com/vv/bigpic/ert39.gif', 145000),
('Ericsson T65', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/ert65.gif', 9000),
('Ericsson T66', NULL, 'https://cdn2.gsmarena.com/vv/bigpic/ert66.gif', 11000),
('Ericsson T68', 'Can be software upgraded to T68i features', 'https://cdn2.gsmarena.com/vv/bigpic/ert68.gif', 20000);
