

CREATE TABLE challenge_phone (
	_id INT NOT NULL PRIMARY KEY COMMENT '',
	name VARCHAR(255) NOT NULL COMMENT '',
	description TEXT DEFAULT NULL COMMENT '',
	image TEXT DEFAULT NULL COMMENT '',
	prize INT NOT NULL COMMENT ''
) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB;